removed_sources:
  CPANPLUS-Shell-Default-Plugins-Prereqs-0.07.tar.gz: 50bfbbd2a6329e2a7124d0a631f3167aff98dde2
sources:
  CPANPLUS-Shell-Default-Plugins-Prereqs-0.10.tar.gz: d5edc542fee58a2522eb33e1c1bbe673b1aa8f69
